### ISSUE TITLE
文字化けします

### ISSUE THREAD

**Issue by hagakenji** [plusone-masaki/csv-plus#101]
・１行しかない（行末が改行ではなくeof）
・最後の２文字が "す。”
この条件のcsvファイルを読むと文字化けします。
![ss](https://user-images.githubusercontent.com/68989125/151090096-cd0eebed-b32f-4cbc-bbfa-2f097f358993.jpg)

**Comment by plusone-masaki** [comment]
不具合の報告をありがとうございます。
いくつか詳細を伺いたいので、下記の質問にご回答いただけますでしょうか。

- 使用されているバージョンを教えていただけますか？
- 文字コードはUTF-8でしょうか。他のコードであれば何を使用しているか教えてください。

**Comment by hagakenji** [comment]
バージョンは0.9.6です
文字コードは添付の例はUTF-8ですが、ShiftJISでも化けます。

**Comment by plusone-masaki** [comment]
ありがとうございます。
文字コード関係ないということは、最後の文字の解析に失敗してそうですね。
修正対応いたします。

**Comment by plusone-masaki** [comment]
v0.9.7 にて修正しました。
行末に改行コードがない場合に文字化けしてしまう不具合となっていました。
