### ISSUE TITLE
行番号の桁数について

### ISSUE THREAD

**Issue by synctam** [plusone-masaki/csv-plus#13]
素晴らしいツールを公開していただき、ありがとうございます。

【状況】
47504行のCSVファイルを読み込んだところ、行番号が４桁までしか表示されません。
【参考資料】
[CSV+のスクリーンショット](https://i.imgur.com/jMcNP72.jpeg)
【環境】
Windows 10 Pro(64bit) バージョン 21H1
CSV-plus 0.7.4(msi インストーラー版)

お時間のあるときで結構ですので、御検討いただけると助かります。

**Comment by plusone-masaki** [comment]
不具合のご報告ありがとうございます！
47504行の表示には成功しているが、行番号が表示しきれていないという不具合ですね。
こちら対応いたします。

**Comment by synctam** [comment]
ありがとうございます、よろしくお願いします。

**Comment by plusone-masaki** [comment]
行番号列の幅について
デフォルトの 50px と、(番号の文字数 * 16px) のどちらか大きい方のピクセル数になるように調整しました。

**Comment by synctam** [comment]
CSV+ 0.7.7 で正常に行番号が表示されることを確認しました。
対応、ありがとうございました。
