### ISSUE TITLE
Windows版で%APPDATA%\csv-plus\historyが無くなり起動ができなくなることがある

### ISSUE THREAD

**Issue by puchi777** [plusone-masaki/csv-plus#133]
いつも利用させて頂いております。ありがとうございます。

Windows版で `%APPDATA%\csv-plus\history` が無いと以下のメッセージボックスが表示され起動ができませんでした。

```
A JavaScript error occurred in the main process

Uncaought Exception: Error: ENOENT: no such file or directory, open %APPDATA%\csv-plus\history
```

突然だったので再現手順が怪しいのですが、以下の場合に該当フォルダが無くなったのかと思います。

1. アプリケーションを起動
2. アップデートの通知が表示されたのでキャンセル
3. 復元されたCSVのタブを全て閉じる
4. アプリケーションを終了
5. 0.9.6 から 0.9.9 にアップデート
6. 起動したら上記のメッセージが表示された

`%APPDATA%\csv-plus\history` をエクスプローラーから作成したところ正常に起動するようになりました。

気になったのでIssueを上げさせて頂きました。どうぞよろしくお願いいたします。

**Comment by TaroMori0321** [comment]
こんにちは。
Mac版をインストールして起動したところ、同じようなエラーが出ました。
私も自己解決できたのですが、念のため報告させていただきます。

```
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/Users/***/Library/Application Support/csv-plus/history/recent-directory'
```

`/Users/***/Library/Application Support/csv-plus/history/recent-directory`を作れば動くのかな
と思い`mkdir`したのですが、今度は以下のエラーが出ました。

```
Uncaught Exception:
Error: EISDIR: illegal operation on a directory, read
```

`recent-directory`はディレクトリではなくファイルですね。
改めて`touch`したところ、正常に起動しました。

何卒よろしくお願い致します。

**Comment by plusone-masaki** [comment]
ご迷惑をおかけしてすみません。
こちら再現できましたので修正版をアップいたします。

**Comment by plusone-masaki** [comment]
本日お昼ごろにリリースした v0.9.10 にて修正しました。
