### ISSUE TITLE
文字化けについて

### ISSUE THREAD

**Issue by synctam** [plusone-masaki/csv-plus#14]
【状況】
特定のＣＳＶファイル（UTF-8）を読み込んだところ、一部文字化けが発生します。
[文字化けの発生しているときのＳＳ](https://imgur.com/AIGouQA)
[文字化け発生箇所の前の行を削除し、文字化けが発生しなくなったときのＳＳ](https://imgur.com/SD0IzcH)

【環境】
Windows 10 Pro(64bit) バージョン 21H1
CSV-plus 0.7.4(msi インストーラー版)

【試してみたこと】
1.BOMの有無は影響ありませんでした。
2.文字化け発生行より前の１行削除すると該当箇所の文字化けは発生しなくなります。

なお、文字化けが発生するファイルが必要な場合は、メールにてお渡しします。
お時間のあるときで結構ですので、御検討いただけると助かります。

**Comment by plusone-masaki** [comment]
不具合のご報告ありがとうございます！
確かに変換が上手くいってないようですね。

調査いたしますので、お手数ですが m_enomoto@plus-one.tech まで対象のファイルをお送り頂けますでしょうか。

**Comment by synctam** [comment]
只今、再現データをメールで送りました。
よろしくお願いいたします。

**Comment by plusone-masaki** [comment]
データをお送りいただきありがとうございました。おかげさまで原因が判明しました。
Streamで読み込む際のチャンクの切れ目が「い」のバイトを分割してしまっているのが原因のようです。
問題の解決にはもう少し時間が必要ですが、対応はできそうです。
![image](https://user-images.githubusercontent.com/29376661/122705745-4da9da00-d291-11eb-8a8c-11aff07d2777.png)

**Comment by synctam** [comment]
CSV+ 0.7.8 で文字化けの発生していたCSVファイルを開き、問題が発生しないことを確認しました。
対応ありがとうございました。
