### ISSUE TITLE
左を押していると上の列に上がっていくのは仕様でしょうか？

### ISSUE THREAD

**Issue by hiroshi-tsuji** [plusone-masaki/csv-plus#18]
お世話になっております。便利ツールの提供ありがとうございます。

さて、表題の件は仕様でしょうか？
行が長い時、先頭に移動して止まる手段がマウス操作しかなくなりそうで、不便に感じました

**Comment by plusone-masaki** [comment]
ご質問ありがとうございます！
現在のところはそういった仕様ですが、確かに先頭で止まるようにしたい気持ちはわかりますので、
メジャーリリースまでに対応できるかは検討してみたいと思います。
