### ISSUE TITLE
Mac OSで、Cmd + Cでのセルコピーができない

### ISSUE THREAD

**Issue by hiroshi-tsuji** [plusone-masaki/csv-plus#19]
もしかしたら仕様なのかもしれませんが、Mac OSでセルのコピーができませんでした
OS versionは11.2.3（20D91）です。

**Comment by plusone-masaki** [comment]
ありがとうございます。
こちらはCtrlとCmdの出し分けができていなかった不具合となりますので、修正いたします。

**Comment by nshoji** [comment]
一応、mac版ですが、Cmd Vでの貼り付けもできません。(右クリックでのメニューに貼り付けが出てこないので別issueでしょうか)

**Comment by plusone-masaki** [comment]
v0.7.7で解消されたと思います。
ダウンロードページから再度ダウンロードしてお試しいただけますか？

**Comment by nshoji** [comment]
@plusone-masaki  確認しました、v0.7.7で解消されました！🎉

**Comment by plusone-masaki** [comment]
ありがとうございます。
確認いただけたようですのでクローズします。
