### ISSUE TITLE
EXE 形式での配布について

### ISSUE THREAD

**Issue by inasato** [plusone-masaki/csv-plus#26]
EXE 形式での配布は、ウイルス対策ソフトなどではじかれてしまうので、Windows インストーラー形式 (MSI) での配布を検討いただけないでしょうか。

**Comment by plusone-masaki** [comment]
MSI形式はインストール先が選べない・拡張子との関連付けがされないなどの各種制約があるため、EXE形式での配布となりました。
インストールができない場合の代替案として、ダウンロードページにZIP形式でインストール不要の実行ファイルを配布していますので、そちらを試してもらうことはできますか？

**Comment by inasato** [comment]
承知いたしました。
