### ISSUE TITLE
ダウンロード時のブロックについて

### ISSUE THREAD

**Issue by inasato** [plusone-masaki/csv-plus#27]
https://www.plus-one.tech/csv-plus/download/
こちらのサイトから Windows EXE 版のダウンロードを Edge や Chrome で行うと、以下のようなメッセージが出てブロックされます。
・Edge
「csv-plus-setup-0.7.6.exe はお使いのデバイスに問題を起こす可能性があるため、ブロックされました。」
・Chrome
「csv-plus-setup-0.7.6.exe は一般的にダウンロードされているファイルではなく危害を及ぼす可能性があります。[破棄]」
回避方法はないかもしれませんが、ダウンロードページで何か「問題ありません」などコメントを入れておくのが良いのではないかと思います。

**Comment by plusone-masaki** [comment]
ご報告ありがとうございます。
確かに、考えられる方法としては exe ファイルを zip で圧縮するなどがありますが手間ですね。
文言で表示しておく程度なら対応できそうですので、やろうと思います。

**Comment by inasato** [comment]
ありがとうございます。サクラエディタなどは exe ファイルを zip で圧縮して配布しているので、それが良いかと思います。
