### ISSUE TITLE
改行コードLFで強制的に保存されます

### ISSUE THREAD

**Issue by renren0817** [plusone-masaki/csv-plus#50]
便利なソフトウェア有難うございます。

Windowsにて現在Ver0.8.1を使用しておりますが、保存すると
強制的に改行コードがLFとなってしまいます。

リリースには以前のVerで修正とありますが、まだ駄目なようです。
確認して頂けると幸いです。

**Comment by plusone-masaki** [comment]
ご報告ありがとうございます。
文字コードと改行コードの処理順が悪かったようで、ただいま v0.8.2 をアップしました。

最新版で再度お試しいただけますでしょうか。

https://www.plus-one.tech/csv-plus/download/

**Comment by renren0817** [comment]
お忙しい中、早々のご対応有難うございます。

改行コードについては、修正されたことが確認出来ました。

ただ、次は文字コードがおかしくなるようです・・・・・・
（こちらではUTF-8（BOM無し）に変更されます）

CSV＋設定上、CR+LF、シフトJISで実行しております。

**Comment by plusone-masaki** [comment]
本当ですね...
テストが整備されてなくてデグレしてしまって申し訳ないです。

今新しいリリースを出しましたので、こちらをご確認ください。
https://www.plus-one.tech/csv-plus/download/

**Comment by renren0817** [comment]
おはようございます。

何度も申し訳ありませんでした。

0.8.3で、問題が解消されていることが確認出来ました。
早々の対応、有難うございます。

CSV+、有効に使用させていただきます。

**Comment by plusone-masaki** [comment]
ご確認ありがとうございます。
こちらのissueは完了にしたいと思います。
