### ISSUE TITLE
(要望)タブ操作

### ISSUE THREAD

**Issue by Leeside18** [plusone-masaki/csv-plus#56]
便利なソフトウェアありがとうございます。

複数のCSVファイルをタブとして開ける点が画期的で愛用させていただいているのですが、Excelのような
`Ctrl + pg up` `Ctrl + pg dn`キーを使ったタブ移動ショートカットなどを追加して頂けないでしょうか？![image](https://user-images.githubusercontent.com/60916716/123735573-7148d200-d8da-11eb-80c8-03a57eef676e.jpeg)

[Microsoft Excel ショートカット](https://support.microsoft.com/ja-jp/office/excel-%E3%81%AE%E3%82%AD%E3%83%BC%E3%83%9C%E3%83%BC%E3%83%89-%E3%82%B7%E3%83%A7%E3%83%BC%E3%83%88%E3%82%AB%E3%83%83%E3%83%88-1798d9d5-842a-42b8-9c99-9b7213f0040f#bkmk_otherwin)

**Comment by plusone-masaki** [comment]
コメント遅くなりました。
Ctrl+PageUpでのタブ移動であれば可能ですので、対応します。

**Comment by plusone-masaki** [comment]
こちらv0.9.2で実装しました。
