### ISSUE TITLE
【要望】Ctrlやcmd+方向キーの操作に対応して欲しい

### ISSUE THREAD

**Issue by k-tsumura331** [plusone-masaki/csv-plus#57]
以下機能が欲しいです。

- Ctrl + 方向キーで入力列の端に移動
- Ctrl + shift + 方向キーで入力列の端まで範囲選択

**Comment by plusone-masaki** [comment]
ご要望ありがとうございます！
確かにその機能は欲しいですよね、対応したいと思います。

**Comment by plusone-masaki** [comment]
v0.9.0にて対応しました！

**Comment by plusone-masaki** [comment]
0.9.0 で端までジャンプ、0.9.2で端まで範囲選択の機能を追加しました。
